### PR TITLE
Milestone 1: TNW Page Responsive Design

### PR DESCRIPTION
**Pull request by jurgen1c**
##### TNW Page Responsive Design 

In this branch we: 

- Ceated semantic HTML & CSS
- Used grid, flexbox & float for layouts
- Created Media Queries for responsiveness 
- Added relevant content & links

### CODE REVIEW

**Comment by mateomh** [comment]
The lighthouse is not passing and we don't know why. It doesn't give a URL report and the recommendations from the extension don't seem to help. We don't know what else to do or where to continue

**Review by voscarmv — CHANGES_REQUESTED** [review]
Hi team,

You need to remove the following file from your repository in order for Lighthouse to work:

https://github.com/mateomh/Responsive-Design/blob/tnw-page/hint-report/file--home-jcg-Documents-Microverse-HTML%2520%26%2520CSS-TNW%2520%2520Page%2520Clone%2520Responsive%2520Design-Responsive-Design.html

 I can not begin a review as your project does not satisfy even the minimum requirement of passing all tests beforehand. However, I will not mark your project as invalid just yet, since the mistake is minor, and to allow you to get a review from the next TSE.

Fix this and submit for review once again!
Happy hacking!

**Comment by voscarmv** [comment]
For future reference:

I experienced this exact problem before. The github automated checks are buggy, and require the user to update some file in order to pass the Lighthouse check. If anybody else encounters the same bug, recommend the user to delete all hint log files, and to then add a small change to some file in the repository in order for the gihub Lighthouse check to respond.

Cheers!

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle:
## Great job so far guys :100:, but in order to make your project approved :checkered_flag: you need to make some minor changes :hammer: :wrench: :toolbox: 

- [x] Remove the logo on the desktop view, leave it only for tablet view and less.
image

- [x] Remove the extras space after the header:
image

- [x] Fix the header and the top articles on tablet view:

| Clone | Original |
|:---:|:---:|
| image | image |

- [x] You are having too much space between your articles, please make it shorter you can make the articles bigger as the original page.
image

- [x] this links should go to the extreme right, instead of using padding and width with percentages you can fix it easily with justify-content: space-between:
image

- [x] same note as for the latest news section:
image

- [x] I have noticed that you have forgotten that there is something called tablet view, please fix it.

- [x] Fix this overlapping on the mobile view.
image

- [x] Fix the header it should match the original:

| Clone | Original |
|:---:|:---:|
| image | image |

### Please make all the required changes before you request another code review.
## Happy Coding :tophat:

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team :hand: 
Status: Changes Required :recycle: 

Seems like there's just one step left :arrow_down: 
- [x]  Space after the header still exists. (Required by the previous TSE)
**Project:** :camera: 
space header
**Original:** :camera_flash: 
origin

That's all. Congratulations on doing all of the other changes...

You can reach out to me through Slack...
With all my respect...

**Review by expjazz — APPROVED** [review]
## Status: Project Approved :clap: 

The page looks awesome, and you worked on what was previously asked. Congratulations :100: 

I will suggest one optional change, so the project looks completely like the original: The TNW logo of the main section (below the nav) needs to disappear in the medium size screen.

As I said, this is optional, so you do not need to ask for a new review. You can move on to the next project.
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Pull request merged**
